### ISSUE TITLE
Bug with Difficulty content

### ISSUE THREAD

**Issue by kvagajack** [Equibit/explorer#14]
Difficulty section shows escaped html content.
Should show a number, e.g. (from `getblockchaininfo` RPC):
- "difficulty": 4.656542373906925e-10

![image](https://user-images.githubusercontent.com/40669118/49229887-76f57880-f3bc-11e8-87d2-f8e3895c1058.png)

**Comment by Eternali** [comment]
When querying /api/getdifficulty, or any api endpoint, the UI reports that "The header content contains invalid characters". Interestingly, when run locally against the same node and database, it works fine.
