### ISSUE TITLE
Demo notes

### ISSUE THREAD

**Issue by kvagajack** [Equibit/explorer#26]
- [x] BTC Price - put N/A
- [x] Coin Supply (EQB) - why its empty?
- [x] Network (GH/s) - check calculation
- [x] remove Movement and Markets
- [x] finding what difficulty level base line is.
- [x] check why `168 blocks 2 connections` is hanging on every page:
![image](https://user-images.githubusercontent.com/40669118/49401042-092ab300-f714-11e8-8d74-2d792e99efe9.png)

**Comment by Eternali** [comment]
The difficulty is simply requested (via the RPC `getdifficulty`) from the connected node and is just displayed as-is.
